[theme]
base="dark"
primaryColor="#0ac398"
font="monospace"

[server]
enableXsrfProtection=false
port = 80

[runner]
fastReruns=true

[client]
toolbarMode="auto"

[browser]
serverAddress = "0.0.0.0"
serverPort = 80
