[theme]
base="dark"
primaryColor="#48bba0"
secondaryBackgroundColor="#32333f"
textColor="#d6d0d0"
font="monospace"

[ui]
hideTopBar = true

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 5

[runner]
fastReruns = true

[client]
showSidebarNavigation = true


